name: Deploy to GitHub Pages

on:
  push:
    branches:
      - all-blocks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Bun
        uses: utooland/setup-utoo@v1

      - name: Install dependencies with Bun
        run: utoo install

      - name: Build project
        run: utoo run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: preview.pro.ant.design
