name: Issue labeled

on:
  issues:
    types: [labeled]

jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'â¤ï¸ help wanted' || github.event.label.name == 'ğŸ¤Welcome PR'
        uses: actions-cool/issues-helper@v1.11
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæˆ‘ä»¬å®Œå…¨åŒæ„ä½ çš„æè®®/åé¦ˆï¼Œæ¬¢è¿ç›´æ¥åœ¨æ­¤ä»“åº“ [åˆ›å»ºä¸€ä¸ª Pull Request](https://help.github.com/en/articles/creating-a-pull-request) æ¥è§£å†³è¿™ä¸ªé—®é¢˜ã€‚è¯·åŠ¡å¿…æä¾›æ”¹åŠ¨æ‰€éœ€ç›¸åº”çš„ changelogã€TypeScript å®šä¹‰ã€æµ‹è¯•ç”¨ä¾‹ã€æ–‡æ¡£ç­‰ï¼Œå¹¶ç¡®ä¿ CI é€šè¿‡ï¼Œæˆ‘ä»¬ä¼šå°½å¿«è¿›è¡Œ Reviewï¼Œæå‰æ„Ÿè°¢å’ŒæœŸå¾…æ‚¨çš„è´¡çŒ®ã€‚

            ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)

      - name: Need Reproduce
        if: github.event.label.name == 'ğŸ¤” Need Reproduce'
        uses: actions-cool/issues-helper@v1.11
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.

            ä½ å¥½ @${{ github.event.issue.user.login }}, æˆ‘ä»¬éœ€è¦ä½ æä¾›ä¸€ä¸ªåœ¨çº¿çš„é‡ç°å®ä¾‹ä»¥ä¾¿äºæˆ‘ä»¬å¸®ä½ æ’æŸ¥é—®é¢˜ã€‚ä½ å¯ä»¥é€šè¿‡ç‚¹å‡» [æ­¤å¤„](https://codesandbox.io/) åˆ›å»ºä¸€ä¸ª codesandbox æˆ–è€…æä¾›ä¸€ä¸ªæœ€å°åŒ–çš„ GitHub ä»“åº“ã€‚

            ![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)
